inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb

Style/Documentation:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
