version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@3.2.0
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          context: dlss
          name: lint          
      - ruby-rails/test-rails:
          context: dlss
          name: test
          api-only: true
      - ruby-rails/docker-publish:
          context: dlss
          name: publish-latest
          image: suldlss/workflow-server
          requires:
            - lint
            - test
          filters:
            branches:
              only:
                - main
