FROM ruby:3.0.3-alpine

ARG BUNDLE_GEMS__CONTRIBSYS__COM
ENV BUNDLE_GEMS__CONTRIBSYS__COM $BUNDLE_GEMS__CONTRIBSYS__COM

# The postgres-client could be eliminated in production
RUN apk --no-cache add \
  git \
  postgresql-dev \
  postgresql-client \
  tzdata

RUN mkdir /app
WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN apk --no-cache add --virtual build-dependencies \
  build-base \
  && bundle install --without production \
&& apk del build-dependencies

COPY . .

LABEL maintainer="Justin Coyne <jcoyne@justincoyne.com>"
ENV RAILS_ENV=production

CMD puma -C config/puma.rb
