FROM ruby:2.5-alpine

# The postgres-client could be eliminated in production
RUN apk --no-cache add \
  git \
  postgresql-dev \
  postgresql-client \
  tzdata

RUN mkdir /app
WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN apk --no-cache add --virtual build-dependencies \
  build-base \
  && bundle install --without production \
&& apk del build-dependencies

COPY . .

LABEL maintainer="Justin Coyne <jcoyne@justincoyne.com>"
ENV RAILS_ENV=production

CMD puma -C config/puma.rb
