dor_services:
  url: 'http://localhost:3003'
  token: secret-token

rabbitmq:
  enabled: false
  hostname: localhost
  vhost: /
  username: guest
  password: guest

redis:
  hostname: localhost
  port: 6379
  db: 0
  namespace: 'resque:development'
